import { Coordinates } from "./Coordinates";

export interface ServiceIncident {
  ADDRESS1: string | null;
  ADDRESS2: string | null;
  ADDRESS3: string | null;
  AREA: string | null;
  CATEGORY: string | null;
  CE_CATEGORY: string | null;
  CITY: string | null;
  CLOSE_DATE: string | null;
  COLLECTION_DAY: string | null;
  CREATED_BY: string | null;
  CREATED_BY_USER: string | null;
  CREATION_DATE: string | null;
  DEPARTMENT: string | null;
  DISTRICT: string | null;
  DIVISION: string | null;
  FOLLOWUP_DATE: string | null;
  GROUP_NAME: string | null;
  INCIDENT_ID: number | null;
  INCIDENT_NUMBER: number | null;
  INCIDENT_RESOLVED_DATE: string | null;
  INCIDENT_TYPE_ID: number | null;
  LAST_MODIFIED_DATE: string | null;
  LAST_UPDATE_DATE: string | null;
  LAST_UPDATE_LOGIN: string | null;
  LAST_UPDATED_BY: string | null;
  MAP_PAGE: string | null;
  NEXT_OPEN_TASK_DATE: string | null;
  NUMBER_OF_TASKS: number | null;
  OWNER_NAME: string | null;
  PARCEL_ID: string | null;
  POSTAL_CODE: number | null;
  REPORTED_DATE: string | null;
  REQUEST_PRIORITY: string | null;
  REQUEST_STATUS: string | null;
  REQUEST_TYPE: string | null;
  RESOLUTION_CODE: string | null;
  RESOLUTION_CODE_MEANING: string | null;
  RESOLUTION_SUMMARY: string | null;
  SR_CREATION_CHANNEL: string | null;
  STATE: string | null;
  STREET_NAME: string | null;
  SUB_DISTRICT: string | null;
  SUMMARY: string | null;
  SWM_CODE: string | null;
  TARGET_BLOCK: number | null;
  ZONE: string | null;
  Location_1: string | null;
  "100_Block_Coordinates": string | null;
  Coordinates: Coordinates | null;
  Status: string;
  Points: number;
}
